/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TrainerImport } from './routes/trainer'
import { Route as TimerImport } from './routes/timer'
import { Route as DevImport } from './routes/dev'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TrainerRoute = TrainerImport.update({
  path: '/trainer',
  getParentRoute: () => rootRoute,
} as any)

const TimerRoute = TimerImport.update({
  path: '/timer',
  getParentRoute: () => rootRoute,
} as any)

const DevRoute = DevImport.update({
  path: '/dev',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dev': {
      preLoaderRoute: typeof DevImport
      parentRoute: typeof rootRoute
    }
    '/timer': {
      preLoaderRoute: typeof TimerImport
      parentRoute: typeof rootRoute
    }
    '/trainer': {
      preLoaderRoute: typeof TrainerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DevRoute,
  TimerRoute,
  TrainerRoute,
])

/* prettier-ignore-end */
